# Header
menu:
  首页: /
  归档: /archives
  分类: /categories
#rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true
aplayer: true

since:

# Miscellaneous
favicon:

# search
search_enable: false

# Hosted by xxxx
coderignt: false

# Tencent analytics ID
#tencent_analytics:

# CNZZ count
cnzz_siteid: